kind: pipeline
name: Build Debian BUSTER Machinekit-HAL and test AMD64

platform:
  arch: amd64

steps:
- name: Build and run tests
  image: eryaf/mk-native_buster
  commands:
  - uname -a
  - id -u
  - id -g
  - sudo apt-get update
  - sudo apt-get -y upgrade
  - cd ~
  - git clone --depth 1 --branch drone-cloud-ci https://github.com/cerna/machinekit-hal mk
  - cd mk
  - debian/configure
  - mk-build-deps -r
  - sudo apt-get -y install ./machinekit-hal-build-deps_1.0_all.deb
  - cd src
  - ./autogen.sh
  - ./configure
  - make
  - sudo make setuid
  - cd ..
  - . ./scripts/rip-environment
  - echo -e 'ANNOUNCE_IPV4=0\nANNOUNCE_IPV6=0' >> etc/machinekit/machinekit.ini
  - runtests tests
---
kind: pipeline
name: Build Debian BUSTER Machinekit-HAL and test ARM64

platform:
  arch: arm64

steps:
- name: Build and run tests
  image: eryaf/mk-native_buster
  commands:
  - uname -a
  - id -u
  - id -g
  - sudo apt-get update
  - sudo apt-get -y upgrade
  - cd ~
  - git clone --depth 1 --branch drone-cloud-ci https://github.com/cerna/machinekit-hal mk
  - cd mk
  - debian/configure
  - mk-build-deps -r
  - sudo apt-get -y install ./machinekit-hal-build-deps_1.0_all.deb
  - cd src
  - ./autogen.sh
  - ./configure
  - make
  - sudo make setuid
  - cd ..
  - . ./scripts/rip-environment
  - echo -e 'ANNOUNCE_IPV4=0\nANNOUNCE_IPV6=0' >> etc/machinekit/machinekit.ini
  - runtests tests

---
kind: pipeline
name: Build Debian BUSTER Machinekit-HAL and test ARM

platform:
  arch: arm

steps:
- name: Build and run tests
  image: eryaf/mk-native_buster
  commands:
  - uname -a
  - id -u
  - id -g
  - sudo apt-get update
  - sudo apt-get -y upgrade
  - cd ~
  - git clone --depth 1 --branch drone-cloud-ci https://github.com/cerna/machinekit-hal mk
  - cd mk
  - debian/configure
  - mk-build-deps -r
  - sudo apt-get -y install ./machinekit-hal-build-deps_1.0_all.deb
  - cd src
  - ./autogen.sh
  - ./configure
  - make
  - sudo make setuid
  - cd ..
  - . ./scripts/rip-environment
  - echo -e 'ANNOUNCE_IPV4=0\nANNOUNCE_IPV6=0' >> etc/machinekit/machinekit.ini
  - runtests tests runtests tests
