kind: pipeline
name: Build Debian Machinekit-HAL and test

platform:
  arch: amd64

steps:
- name: machinekit-registry
  image: registry:2
  detach: true
  pull: if-not-exists

- name: Docker maybe
  image: plugins/docker
  settings:
    repo: machinekit-registry:5000/foo/bar
    dockerfile: scripts/containers/buildsystem/debian/Dockerfile.native
    registry: machinekit-registry:5000

- name: Print environ
  image: debian:buster
  pull: if-not-exists
  commands:
  - printenv
  - uname -a
  - uname -r
