kind: pipeline
name: Build Debian Machinekit-HAL and test

platform:
  arch: amd64

steps:
- name: machinekit-registry
  image: registry:2
  detach: true
  pull: if-not-exists

- name: Docker maybe
  image: plugins/docker
  settings:
    dockerfile: scripts/containers/buildsystem/debian/Dockerfile.native
    insecure: true
    registry: machinekit-registry:5000
    repo: machinekit-registry:5000/test

- name: Test image
  image: machinekit-registry:5000/test
  commands:
  - uname -a

- name: Print environ
  image: debian:buster
  pull: if-not-exists
  commands:
  - printenv
  - uname -a
  - uname -r
