kind: pipeline
name: Build Debian Machinekit-HAL and test

platform:
  arch: amd64

steps:
- name: machinekit-registry.local
  image: registry:2
  detach: true
  pull: if-not-exists

- name: Docker maybe
  image: plugins/docker
  settings:
    repo: machinekit-registry.local/foo/bar
    dockerfile: scripts/containers/buildsystem/debian/Dockerfile.native
    registry: machinekit-registry.local

- name: Print environ
  image: debian:buster
  pull: if-not-exists
  commands:
  - printenv
  - uname -a
  - uname -r

- name: test
  image: redis
  pull: if-not-exists
  commands:
  - sleep 5
  - redis-cli -h redis ping
  - redis-cli -h redis set FOO bar
  - redis-cli -h redis get FOO